version: '3'


volumes:
  grafana-storage:
  prometheus-storage:
services:
  app1:
    build: .
    container_name: "app1"
    env_file: 
      - ".env"
    ports:
      - "3001:3000"
  app2:
    build: .
    container_name: "app2"
    env_file: 
      - ".env"
    ports:
      - "3002:3000"
  prometheus:
    image: prom/prometheus:v2.36.1
    restart: "no"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=60d'
  grafana:
    image: grafana/grafana:9.0.0
    restart: "no"
    depends_on:
      - prometheus
    ports:
      - "13000:3000"
    volumes:
      - ./monitoring/grafana:/etc/grafana:ro
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=grafadmin
      - GF_SECURITY_ADMIN_PASSWORD=toto
      - GF_USERS_ALLOW_SIGN_UP=false



