{
 "title": "App monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Intance",
    "query": {
     "query": "label_values(myapp_healthcheck, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incident counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status) (myapp_incident_status_old)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incident counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status) (myapp_incident_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incident durations (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg by(quantile) (myapp_incident_timing) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "instance" },
  {
   "title": "Service A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myapp_healthcheck{service=\"serviceA\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myapp_healthcheck{service=\"serviceA\", instance=\"$instance\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(myapp_healthcheck{service=\"serviceA\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Incidents for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } }
 ]
}