global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Prometheus
  - job_name: 'Prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'App'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']
